# Generated by Django 2.0 on 2019-05-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamachievement',
            name='picture',
        ),
    ]
