# Generated by Django 2.0 on 2019-05-17 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_teamachievement_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file', to='api.Achievement')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file', to='api.Team')),
            ],
        ),
    ]
