# Generated by Django 2.0 on 2019-05-22 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_teamachievement_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamachievement',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_achievements', to='api.File'),
        ),
    ]
