# Generated by Django 2.0 on 2019-05-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190517_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamachievement',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teamachievement',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
