# Generated by Django 2.0 on 2019-05-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190517_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamachievement',
            name='created_by',
        ),
    ]
